<?php 
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2012 Sinabs (http://www.sinabs.fr)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php 
	$_mail = $this->getMail(); 
	$_helper = $this->helper('automaticresponse');
?>
<div id="reply_form">
	<span class="field-row">
		<label class="normal" for="comment"><?php echo $this->__('Comment'); ?></label>
		<textarea id="comment" name="comment" id="comment" rows="3" cols="5" style="height:6em; width:99%"></textarea>
	</span>
	<div class="f-left">
		<input name="is_customer_notified" type="checkbox" id="is_customer_notified" value="1" />
		<label class="normal" for="is_customer_notified">Avertir le client</label>
	</div>
	<div class="f-right">
		<button type="button" class="scalable save" onclick="submitAndReloadArea($('reply_form').parentNode, '<?php echo $this->getUrl('*/*/sendComment', array('id' => $_mail->getId())); ?>');"><span><?php echo $this->__('Submit'); ?></span></button>
	</div>
	<div class="clear"></div>
</div>
<div class="divider"></div>
<ul class="note-list" id="comment-list">
	<?php if ($_mail->getReply() !== null) : ?>
		<?php $reply = $_helper->sortByDateDesc(unserialize($_mail->getReply())); ?>
		<?php foreach ($reply as $_reply) : ?>
		<li>
			<strong><?php echo Mage::helper('core')->formatDate($_reply['created_at'], 'medium', true); ?></strong>
			<p><?php echo nl2br($_reply['comment']); ?></p>
			<small>
				<?php echo $this->__('Customer'); ?>
				<?php if ($_reply['is_customer_notified']) : ?>
					<?php echo $this->__('Notified'); ?>
					<img src="<?php echo $this->getSkinUrl('images/ico_success.gif') ?>" width="16px" height="16px" alt="" />
				<?php else : ?>
					<?php echo $this->__('Not Notified'); ?>
				<?php endif; ?>
			</small>
		</li>
		<?php endforeach; ?>
	<?php else : ?>
	<li><strong><?php echo $this->__('No answer'); ?></strong></li>
	<?php endif; ?>
</ul>