<?php 
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2012 Sinabs (http://www.sinabs.fr)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php $_mail = $this->getMail(); ?>
<div class="box-left">
	<div class="entry-edit">
		<div class="entry-edit-head"><strong><?php echo $this->__('Email #%s', $_mail->getId()); ?></strong></div>
		<div class="fieldset">
			<table cellspacing="0" class="form-list">
				<tbody>
					<tr>
						<td class="label"><label><?php echo $this->__('Date'); ?></label></td>
						<td><strong><?php echo Mage::helper('core')->formatDate($_mail->getDate(), 'medium', true); ?></strong></td>
					</tr>
					<tr>
						<td class="label"><label><?php echo $this->__('Name'); ?></label></td>
						<td><strong><?php echo $_mail->getName(); ?></strong></td>
					</tr>
					<tr>
						<td class="label"><label><?php echo $this->__('Email'); ?></label></td>
						<td><strong><a href="mailto:<?php echo $_mail->getEmail(); ?>"><?php echo $_mail->getEmail(); ?></a></strong></td>
					</tr>
					<tr>
						<td class="label"><label><?php echo $this->__('Phone'); ?></label></td>
						<td><strong><?php echo $_mail->getPhone(); ?></strong></td>
					</tr>
					<tr>
						<td class="label"><label><?php echo $this->__('Comment'); ?></label></td>
						<td><strong><?php echo nl2br($_mail->getComment()); ?></strong></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>
<div class="box-right">
	<div class="entry-edit">
		<div class="entry-edit-head"><strong><?php echo $this->__('Reply to %s', $_mail->getEmail()); ?></strong></div>
		<div class="fieldset">
			<?php echo $this->getChildHtml('automaticresponse_comment_list'); ?>
		</div>
	</div>
</div>
<div class="clear"></div>